-- Backfills tracked migrations for 7 tables and 2 enums that exist in the
-- Prisma schema (prisma/non-market-data/schema.prisma) and in production,
-- but that no migration ever created: they were applied with `prisma db push`
-- outside migration history (same drift class as
-- 20260830020000_backfill_marketing_assets).
--
--   enums:  LoginStatus, SecurityAlertType
--   tables: user_sessions, login_history, security_alerts, UserAppearance,
--           token_usage_log, Drawing, DrawingAlert
--   columns: User.twoFactorEnabled, twoFactorSecret, twoFactorBackupCodes,
--            twoFactorVerifiedAt
--
-- Without this, `prisma migrate deploy` on a fresh database (CI's api-tests
-- job) fails at 20260904120000_default_theme_light with
-- `relation "UserAppearance" does not exist`. Timestamped to apply just
-- before it; no later migration alters any of these tables.
--
-- DDL generated by `prisma migrate diff --from-empty --to-schema
-- prisma/non-market-data/schema.prisma`, then guarded: every statement is
-- IF NOT EXISTS or checks pg_type / pg_constraint first, so on a database
-- that already has these objects (production) this is a no-op.
--
-- Verified: all migrations replay onto an empty Postgres 16, and the result
-- then diffs clean against both Prisma schemas for every missing object.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'LoginStatus') THEN
    CREATE TYPE "LoginStatus" AS ENUM ('SUCCESS', 'FAILED', 'BLOCKED');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SecurityAlertType') THEN
    CREATE TYPE "SecurityAlertType" AS ENUM ('NEW_DEVICE_LOGIN', 'PASSWORD_CHANGED', 'EMAIL_CHANGED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', 'SUSPICIOUS_LOGIN', 'ACCOUNT_LOCKED');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "user_sessions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "userAgent" TEXT,
    "ipAddress" TEXT,
    "deviceType" TEXT,
    "browser" TEXT,
    "browserVersion" TEXT,
    "os" TEXT,
    "osVersion" TEXT,
    "country" TEXT,
    "city" TEXT,
    "region" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastActiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "sessionToken" TEXT,

    CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "login_history" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "LoginStatus" NOT NULL,
    "provider" TEXT NOT NULL,
    "userAgent" TEXT,
    "deviceType" TEXT,
    "browser" TEXT,
    "browserVersion" TEXT,
    "os" TEXT,
    "osVersion" TEXT,
    "ipAddress" TEXT,
    "country" TEXT,
    "city" TEXT,
    "region" TEXT,
    "deviceFingerprint" TEXT,
    "isNewDevice" BOOLEAN NOT NULL DEFAULT false,
    "failureReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "login_history_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "security_alerts" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "SecurityAlertType" NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "ipAddress" TEXT,
    "deviceInfo" TEXT,
    "location" TEXT,
    "emailSent" BOOLEAN NOT NULL DEFAULT false,
    "emailSentAt" TIMESTAMP(3),
    "read" BOOLEAN NOT NULL DEFAULT false,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "security_alerts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "UserAppearance" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "theme" TEXT NOT NULL DEFAULT 'light',
    "accent" TEXT NOT NULL DEFAULT 'amber',
    "chartUpColor" TEXT NOT NULL DEFAULT '#00fbff',
    "chartDownColor" TEXT NOT NULL DEFAULT '#fb00ff',
    "gridOpacity" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserAppearance_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "token_usage_log" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "promptTokens" INTEGER NOT NULL,
    "imageTokens" INTEGER NOT NULL DEFAULT 0,
    "completionTokens" INTEGER NOT NULL,
    "estimatedCostUsd" DOUBLE PRECISION NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "token_usage_log_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Drawing" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "timeframe" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "anchors" JSONB NOT NULL,
    "style" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Drawing_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DrawingAlert" (
    "id" TEXT NOT NULL,
    "drawingId" TEXT NOT NULL,
    "alertId" TEXT NOT NULL,
    "targetLevel" TEXT NOT NULL,
    "direction" TEXT NOT NULL DEFAULT 'either',
    "tolerance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "cooldownSec" INTEGER NOT NULL DEFAULT 60,
    "oneShot" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DrawingAlert_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "user_sessions_sessionToken_key" ON "user_sessions"("sessionToken");

CREATE INDEX IF NOT EXISTS "user_sessions_userId_idx" ON "user_sessions"("userId");

CREATE INDEX IF NOT EXISTS "user_sessions_sessionToken_idx" ON "user_sessions"("sessionToken");

CREATE INDEX IF NOT EXISTS "user_sessions_isActive_idx" ON "user_sessions"("isActive");

CREATE INDEX IF NOT EXISTS "user_sessions_lastActiveAt_idx" ON "user_sessions"("lastActiveAt");

CREATE INDEX IF NOT EXISTS "login_history_userId_idx" ON "login_history"("userId");

CREATE INDEX IF NOT EXISTS "login_history_userId_createdAt_idx" ON "login_history"("userId", "createdAt");

CREATE INDEX IF NOT EXISTS "login_history_ipAddress_idx" ON "login_history"("ipAddress");

CREATE INDEX IF NOT EXISTS "login_history_deviceFingerprint_idx" ON "login_history"("deviceFingerprint");

CREATE INDEX IF NOT EXISTS "login_history_createdAt_idx" ON "login_history"("createdAt");

CREATE INDEX IF NOT EXISTS "security_alerts_userId_idx" ON "security_alerts"("userId");

CREATE INDEX IF NOT EXISTS "security_alerts_userId_read_idx" ON "security_alerts"("userId", "read");

CREATE INDEX IF NOT EXISTS "security_alerts_type_idx" ON "security_alerts"("type");

CREATE INDEX IF NOT EXISTS "security_alerts_createdAt_idx" ON "security_alerts"("createdAt");

CREATE UNIQUE INDEX IF NOT EXISTS "UserAppearance_userId_key" ON "UserAppearance"("userId");

CREATE INDEX IF NOT EXISTS "UserAppearance_userId_idx" ON "UserAppearance"("userId");

CREATE INDEX IF NOT EXISTS "token_usage_log_userId_timestamp_idx" ON "token_usage_log"("userId", "timestamp");

CREATE INDEX IF NOT EXISTS "Drawing_userId_idx" ON "Drawing"("userId");

CREATE INDEX IF NOT EXISTS "Drawing_symbol_timeframe_idx" ON "Drawing"("symbol", "timeframe");

CREATE INDEX IF NOT EXISTS "Drawing_userId_symbol_timeframe_idx" ON "Drawing"("userId", "symbol", "timeframe");

CREATE UNIQUE INDEX IF NOT EXISTS "DrawingAlert_alertId_key" ON "DrawingAlert"("alertId");

CREATE INDEX IF NOT EXISTS "DrawingAlert_drawingId_idx" ON "DrawingAlert"("drawingId");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UserAppearance_userId_fkey') THEN
    ALTER TABLE "UserAppearance" ADD CONSTRAINT "UserAppearance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'token_usage_log_userId_fkey') THEN
    ALTER TABLE "token_usage_log" ADD CONSTRAINT "token_usage_log_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Drawing_userId_fkey') THEN
    ALTER TABLE "Drawing" ADD CONSTRAINT "Drawing_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'DrawingAlert_drawingId_fkey') THEN
    ALTER TABLE "DrawingAlert" ADD CONSTRAINT "DrawingAlert_drawingId_fkey" FOREIGN KEY ("drawingId") REFERENCES "Drawing"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'DrawingAlert_alertId_fkey') THEN
    ALTER TABLE "DrawingAlert" ADD CONSTRAINT "DrawingAlert_alertId_fkey" FOREIGN KEY ("alertId") REFERENCES "Alert"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorSecret" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorBackupCodes" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorVerifiedAt" TIMESTAMP(3);
