# RAG Branch Demo

# MCP Server
servers:
  benchmark: servers/benchmark
  retriever: servers/retriever
  prompt: servers/prompt
  generation: servers/generation
  evaluation: servers/evaluation
  custom: servers/custom
  router: servers/router

# MCP Client Pipeline
pipeline:
  - benchmark.get_data
  - retriever.retriever_init
  - generation.generation_init
  - retriever.retriever_search
  - loop:
      times: 10
      steps:
        - prompt.check_passages
        - generation.generate
        - branch:
            router:
              - router.check_model_state
            branches:
              continue:
                - prompt.gen_subq
                - generation.generate:
                    output:
                      ans_ls: subq_ls
                - retriever.retriever_search:
                    input:
                      query_list: subq_ls
                    output:
                      ret_psg: temp_psg
                - custom.merge_passages
              stop: []
  - prompt.qa_rag_boxed
  - generation.generate
  - custom.output_extract_from_boxed
  - evaluation.evaluate
