# Vanilla VLM Demo

# MCP Server
servers:
  benchmark: servers/benchmark
  prompt: servers/prompt
  generation: servers/generation
  evaluation: servers/evaluation
  custom: servers/custom

# MCP Client Pipeline
pipeline:
  - benchmark.get_data
  - generation.generation_init
  - prompt.qa_boxed
  - generation.multimodal_generate
  - custom.output_extract_from_boxed
  - evaluation.evaluate
