# VisRAG Demo

# MCP Server
servers:
  benchmark: servers/benchmark
  retriever: servers/retriever
  prompt: servers/prompt
  generation: servers/generation

# MCP Client Pipeline
pipeline:
  - benchmark.get_data
  - retriever.retriever_init
  - retriever.retriever_search
  - generation.generation_init
  - prompt.qa_boxed
  - generation.multimodal_generate:
      input:
        multimodal_path: ret_psg
