# WebNote Demo with Web Search API

# MCP Server
servers:
  benchmark: servers/benchmark
  generation: servers/generation
  retriever: servers/retriever
  prompt: servers/prompt
  router: servers/router

# MCP Client Pipeline
pipeline:
  - benchmark.get_data
  - generation.generation_init
  - prompt.webnote_gen_plan
  - generation.generate:
      output:
        ans_ls: plan_ls
  - prompt.webnote_init_page
  - generation.generate:
      output:
        ans_ls: page_ls
  - loop:
      times: 10
      steps:
        - branch:
            router:
              - router.webnote_check_page
            branches:
              incomplete:
                - prompt.webnote_gen_subq
                - generation.generate:
                    output:
                      ans_ls: subq_ls
                - retriever.retriever_tavily_search:
                    input:
                      query_list: subq_ls
                    output:
                      ret_psg: psg_ls
                - prompt.webnote_fill_page
                - generation.generate:
                    output:
                      ans_ls: page_ls
              complete: []
  - prompt.webnote_gen_answer
  - generation.generate
