// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from 'npm:@lovable.dev/mcp-js@0.26.2';

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from 'npm:@lovable.dev/mcp-js@0.26.2';

// src/lib/mcp/supabase.ts
import { createClient } from 'npm:@supabase/supabase-js@^2.90.1';
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(['SUPABASE_URL', 'VITE_SUPABASE_URL']);
  if (!url) throw new Error('SUPABASE_URL (or VITE_SUPABASE_URL) is required');
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    'SUPABASE_PUBLISHABLE_KEY',
    'VITE_SUPABASE_PUBLISHABLE_KEY',
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv('SUPABASE_PUBLISHABLE_KEYS');
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)]
          .find(
            (v) =>
              typeof v === 'string' && v.trim().startsWith('sb_publishable_')
          )
          ?.trim();
        if (key) return key;
      }
    } catch {}
  }
  const legacy = configuredEnv(['SUPABASE_ANON_KEY', 'VITE_SUPABASE_ANON_KEY']);
  if (legacy) return legacy;
  throw new Error(
    'SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required'
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token)
    throw new Error('supabaseForUser requires a verified OAuth token');
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: 'get_profile',
  title: 'Get my profile',
  description:
    "Get the signed-in user's profile (display name, avatar, preferences).",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false,
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: 'text', text: 'Not authenticated' }],
        isError: true,
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase
      .from('profiles')
      .select(
        'id, display_name, avatar_url, preferences, created_at, updated_at'
      )
      .eq('id', ctx.getUserId())
      .maybeSingle();
    if (error)
      return {
        content: [{ type: 'text', text: error.message }],
        isError: true,
      };
    if (!data)
      return {
        content: [{ type: 'text', text: 'No profile found for this user.' }],
      };
    return {
      content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data },
    };
  },
});

// src/lib/mcp/tools/update-profile.ts
import { defineTool as defineTool2 } from 'npm:@lovable.dev/mcp-js@0.26.2';
import { z } from 'npm:zod@^3.25.76';
var update_profile_default = defineTool2({
  name: 'update_profile',
  title: 'Update my profile',
  description: "Update the signed-in user's display name and/or avatar URL.",
  inputSchema: {
    display_name: z
      .string()
      .trim()
      .min(1)
      .max(80)
      .optional()
      .describe('New display name.'),
    avatar_url: z.string().url().optional().describe('New avatar image URL.'),
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    openWorldHint: false,
  },
  handler: async ({ display_name, avatar_url }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: 'text', text: 'Not authenticated' }],
        isError: true,
      };
    }
    if (display_name === void 0 && avatar_url === void 0) {
      return {
        content: [
          { type: 'text', text: 'Provide display_name or avatar_url.' },
        ],
        isError: true,
      };
    }
    const supabase = supabaseForUser(ctx);
    const patch = {};
    if (display_name !== void 0) patch.display_name = display_name;
    if (avatar_url !== void 0) patch.avatar_url = avatar_url;
    const { data, error } = await supabase
      .from('profiles')
      .update(patch)
      .eq('id', ctx.getUserId())
      .select('id, display_name, avatar_url')
      .maybeSingle();
    if (error)
      return {
        content: [{ type: 'text', text: error.message }],
        isError: true,
      };
    return {
      content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data },
    };
  },
});

// src/lib/mcp/index.ts
var projectRef = 'srtfopblzhtesbvaeyct';
var mcp_default = defineMcp({
  name: 'shared-app-engine',
  title: 'Shared App Engine',
  version: '0.1.0',
  instructions:
    "Tools for Shared App Engine. Use `get_profile` to read the signed-in user's profile and `update_profile` to change their display name or avatar.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: 'authenticated',
  }),
  tools: [get_profile_default, update_profile_default],
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from 'npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase';
Deno.serve(createSupabaseHandler(mcp_default, { functionName: 'mcp' }));
