-- Extended indicator statistics: 50 new nullable columns on indicator_statistics.
--   * 40 from the uniform schema the 10 regression-fit indicators now emit
--     ([FIT WINDOW], [PRICE CONTEXT], [CHANNEL GEOMETRY], both
--     [RESIDUAL DIAGNOSTICS] blocks)
--   * 10 sr_* calibration-provenance fields from
--     SupportAndResistantAutoCalibration, whose statistic file was previously
--     dropped in full. sr_1..sr_8 are NOT here -- those already reach Postgres
--     through market_data's 95 columns; these record WHY those levels exist.
--
-- Generated by `prisma migrate diff` against the previous schema, not hand-written.
--
-- SAFE TO APPLY AT ANY TIME, INDEPENDENTLY OF THE INDICATOR REBUILD.
-- Every statement is a nullable ADD COLUMN with no default, so it rewrites no
-- existing row and existing history keeps reading exactly as before. Rows
-- written before the rebuilt .ex5 are deployed simply carry NULL here.
--
-- ROLLOUT ORDER (the reverse order is the one that loses data):
--   1. this migration
--   2. railway-gateway  -- it auto-deploys from `main`, and the statistics
--      contract sets additionalProperties:false with forbidNonWhitelisted:true.
--      This release ALSO widens the closed `source` enum from 10 to 11 to admit
--      'sr_levels', and the statistics POST is BATCHED: a single element
--      carrying a source the deployed gateway does not know 400s the WHOLE
--      request, and the push worker quarantines every snapshot in it to
--      rejected_statistics.jsonl AND stamps synced_at -- recoverable only by
--      hand via replay_quarantine.py.
--   3. the VPS collector + the recompiled indicator binaries
--
-- NULL here always means "not measured", never zero: 0.0 is a real reading for
-- most of these (a zero residual, a symmetric channel, no breaches), and for
-- the single-line indicators the channel fields are NULL because there is no
-- channel to measure -- not because nothing was found.
-- AlterTable
ALTER TABLE "indicator_statistics" ADD COLUMN     "bars_available" INTEGER,
ADD COLUMN     "baseline_coverage_n" INTEGER,
ADD COLUMN     "baseline_coverage_rate" DOUBLE PRECISION,
ADD COLUMN     "baseline_value" DOUBLE PRECISION,
ADD COLUMN     "breach_above_n" INTEGER,
ADD COLUMN     "breach_below_n" INTEGER,
ADD COLUMN     "centroids_used" INTEGER,
ADD COLUMN     "channel_asymmetry" DOUBLE PRECISION,
ADD COLUMN     "channel_position" DOUBLE PRECISION,
ADD COLUMN     "channel_width" DOUBLE PRECISION,
ADD COLUMN     "crossings_in_window_n" INTEGER,
ADD COLUMN     "dist_to_baseline" DOUBLE PRECISION,
ADD COLUMN     "dist_to_loedt" DOUBLE PRECISION,
ADD COLUMN     "dist_to_uoedt" DOUBLE PRECISION,
ADD COLUMN     "first_crossing_ts" INTEGER,
ADD COLUMN     "last_crossing_ts" INTEGER,
ADD COLUMN     "leftmost_bar_index" INTEGER,
ADD COLUMN     "line_span_bars" INTEGER,
ADD COLUMN     "live_close" DOUBLE PRECISION,
ADD COLUMN     "loedt_value" DOUBLE PRECISION,
ADD COLUMN     "max_excursion_above" DOUBLE PRECISION,
ADD COLUMN     "max_excursion_below" DOUBLE PRECISION,
ADD COLUMN     "resid_a_dw" DOUBLE PRECISION,
ADD COLUMN     "resid_a_mae" DOUBLE PRECISION,
ADD COLUMN     "resid_a_max" DOUBLE PRECISION,
ADD COLUMN     "resid_a_mean" DOUBLE PRECISION,
ADD COLUMN     "resid_a_n" INTEGER,
ADD COLUMN     "resid_a_sd" DOUBLE PRECISION,
ADD COLUMN     "resid_b_dw" DOUBLE PRECISION,
ADD COLUMN     "resid_b_mae" DOUBLE PRECISION,
ADD COLUMN     "resid_b_max" DOUBLE PRECISION,
ADD COLUMN     "resid_b_mean" DOUBLE PRECISION,
ADD COLUMN     "resid_b_n" INTEGER,
ADD COLUMN     "resid_b_sd" DOUBLE PRECISION,
ADD COLUMN     "sr_dist_resistance_pts" INTEGER,
ADD COLUMN     "sr_dist_support_pts" INTEGER,
ADD COLUMN     "sr_fractals_n" INTEGER,
ADD COLUMN     "sr_iqr" DOUBLE PRECISION,
ADD COLUMN     "sr_macro_clusters" INTEGER,
ADD COLUMN     "sr_nearest_resistance" DOUBLE PRECISION,
ADD COLUMN     "sr_nearest_support" DOUBLE PRECISION,
ADD COLUMN     "sr_optimal_step" DOUBLE PRECISION,
ADD COLUMN     "sr_q25" DOUBLE PRECISION,
ADD COLUMN     "sr_q75" DOUBLE PRECISION,
ADD COLUMN     "uoedt_value" DOUBLE PRECISION,
ADD COLUMN     "visual_window_bars" INTEGER,
ADD COLUMN     "window_high" DOUBLE PRECISION,
ADD COLUMN     "window_low" DOUBLE PRECISION,
ADD COLUMN     "window_range" DOUBLE PRECISION,
ADD COLUMN     "window_span_bars" INTEGER;
