-- DavinTrade Global SaaS Billing & Multi-Jurisdiction Tax spec
-- (davintrade-vat-stack/DavinTrade Architecture Design - Global SaaS Billing
-- & Multi-Jurisdiction Tax.md, Sections 5.1/5.2). Purely additive: one new
-- table + two indexes + one view. Does not touch any existing table, so it
-- carries none of the "db push diffs the whole shared database" risk
-- documented in CLAUDE.md/LESSONS-LEARNED.md L6 -- generated by hand instead
-- of `prisma migrate dev`/`db push` anyway, per that same established
-- pattern (see Session 11-3, 8-2, 2-3).

-- CreateTable
CREATE TABLE "Invoice" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "subscriptionId" TEXT,
    "stripeInvoiceId" TEXT NOT NULL,
    "stripeCustomerId" TEXT NOT NULL,
    "amountTotal" DECIMAL(65,30) NOT NULL,
    "taxAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "taxRate" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "taxCountry" TEXT NOT NULL,
    "customerTaxId" TEXT,
    "reverseCharge" BOOLEAN NOT NULL DEFAULT false,
    "invoicePdf" TEXT,
    "hostedInvoiceUrl" TEXT,
    "paidAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Invoice_stripeInvoiceId_key" ON "Invoice"("stripeInvoiceId");

-- CreateIndex
CREATE INDEX "Invoice_userId_idx" ON "Invoice"("userId");

-- CreateIndex
CREATE INDEX "Invoice_stripeCustomerId_idx" ON "Invoice"("stripeCustomerId");

-- CreateIndex
CREATE INDEX "Invoice_taxCountry_idx" ON "Invoice"("taxCountry");

-- CreateIndex
CREATE INDEX "Invoice_paidAt_idx" ON "Invoice"("paidAt");

-- Rolling 12-month sales/tax threshold monitoring view (Section 5.2).
-- Drives the EU Non-Union OSS quarterly export and the UK GBP90k /
-- US state-nexus watch lists -- read-only, recomputed on every query, no
-- materialization/refresh job needed at this volume.
CREATE OR REPLACE VIEW "v_country_trailing_12m_sales" AS
SELECT
    "taxCountry",
    "currency",
    COUNT("id") AS total_transactions,
    SUM("amountTotal") AS gross_sales_12m,
    SUM("taxAmount") AS total_tax_collected_12m
FROM "Invoice"
WHERE "paidAt" >= NOW() - INTERVAL '12 months'
GROUP BY "taxCountry", "currency"
ORDER BY gross_sales_12m DESC;
