#!/bin/bash

# ============================================================================
# Generate TypeScript Types from OpenAPI Specifications
# ============================================================================
#
# This script generates TypeScript types from Backend Stack B OpenAPI specs.
# Run this whenever OpenAPI contracts are updated.
#
# Usage:
#   npm run generate:types
#   or
#   ./scripts/generate-types.sh
#
# Multi-Backend Architecture - Simplified (2 backends)
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Generating TypeScript Types from OpenAPI Specs${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if openapi-typescript is installed
if ! npm list openapi-typescript > /dev/null 2>&1; then
  echo -e "${YELLOW}⚠️  openapi-typescript not found. Installing...${NC}"
  npm install -D openapi-typescript
  echo ""
fi

# Define paths
BACKEND_STACK_B_DIR="../backend-stack-b/openapi"
FRONTEND_TYPES_DIR="./types/api"

# Create types directory if it doesn't exist
mkdir -p "$FRONTEND_TYPES_DIR"

echo -e "${GREEN}📁 Output directory: $FRONTEND_TYPES_DIR${NC}"
echo ""

# ============================================================================
# Generate types for Backend Stack B
# ============================================================================

echo -e "${BLUE}🔄 Generating types for Backend Stack B...${NC}"
echo ""

# Part 10: Watchlist API
if [ -f "$BACKEND_STACK_B_DIR/watchlist-api.yaml" ]; then
  echo -e "${YELLOW}  → Watchlist API (Part 10)${NC}"
  npx openapi-typescript "$BACKEND_STACK_B_DIR/watchlist-api.yaml" \
    --output "$FRONTEND_TYPES_DIR/stack-b-watchlist.ts"
  echo -e "${GREEN}    ✓ Generated: stack-b-watchlist.ts${NC}"
else
  echo -e "${RED}    ✗ Skipped: watchlist-api.yaml not found${NC}"
fi

# Part 11: Alerts API
if [ -f "$BACKEND_STACK_B_DIR/alerts-api.yaml" ]; then
  echo -e "${YELLOW}  → Alerts API (Part 11)${NC}"
  npx openapi-typescript "$BACKEND_STACK_B_DIR/alerts-api.yaml" \
    --output "$FRONTEND_TYPES_DIR/stack-b-alerts.ts"
  echo -e "${GREEN}    ✓ Generated: stack-b-alerts.ts${NC}"
else
  echo -e "${RED}    ✗ Skipped: alerts-api.yaml not found${NC}"
fi

# Part 15: Notifications API
if [ -f "$BACKEND_STACK_B_DIR/notifications-api.yaml" ]; then
  echo -e "${YELLOW}  → Notifications API (Part 15)${NC}"
  npx openapi-typescript "$BACKEND_STACK_B_DIR/notifications-api.yaml" \
    --output "$FRONTEND_TYPES_DIR/stack-b-notifications.ts"
  echo -e "${GREEN}    ✓ Generated: stack-b-notifications.ts${NC}"
else
  echo -e "${RED}    ✗ Skipped: notifications-api.yaml not found${NC}"
fi

# Parts 22-23: Analytics API
if [ -f "$BACKEND_STACK_B_DIR/analytics-api.yaml" ]; then
  echo -e "${YELLOW}  → Analytics API (Parts 22-23)${NC}"
  npx openapi-typescript "$BACKEND_STACK_B_DIR/analytics-api.yaml" \
    --output "$FRONTEND_TYPES_DIR/stack-b-analytics.ts"
  echo -e "${GREEN}    ✓ Generated: stack-b-analytics.ts${NC}"
else
  echo -e "${RED}    ✗ Skipped: analytics-api.yaml not found${NC}"
fi

echo ""

# ============================================================================
# Create index file for easy imports
# ============================================================================

echo -e "${BLUE}📝 Creating index file...${NC}"

cat > "$FRONTEND_TYPES_DIR/index.ts" << 'EOF'
/**
 * API Types - Auto-generated from OpenAPI Specifications
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: npm run generate:types
 * Last generated: $(date)
 *
 * Multi-Backend Architecture - Simplified (2 backends)
 */

// Backend Stack B Types
export * from './stack-b-watchlist';
export * from './stack-b-alerts';
export * from './stack-b-notifications';
export * from './stack-b-analytics';
EOF

echo -e "${GREEN}✓ Created: index.ts${NC}"
echo ""

# ============================================================================
# Summary
# ============================================================================

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Type generation complete!${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Generated types location:${NC}"
echo -e "  $FRONTEND_TYPES_DIR/"
echo ""
echo -e "${YELLOW}Usage in code:${NC}"
echo -e "  ${GREEN}import type { paths } from '@/types/api/stack-b-watchlist';${NC}"
echo -e "  ${GREEN}import type { components } from '@/types/api/stack-b-alerts';${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Review generated types in ${BLUE}$FRONTEND_TYPES_DIR/${NC}"
echo -e "  2. Update API clients to use these types"
echo -e "  3. Run ${BLUE}npm run type-check${NC} to verify types"
echo ""
echo -e "${YELLOW}Note:${NC}"
echo -e "  Re-run this script whenever OpenAPI contracts are updated:"
echo -e "  ${BLUE}npm run generate:types${NC}"
echo ""
