// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by railway-gateway/scripts/generate-market-data-dto.js from
// gateway_contract_currency_gold_indices.schema.json. Re-run `npm run generate:dto`
// after any change to that schema file.
import { IsString, IsNumber, IsInt, IsIn } from 'class-validator';

export class CurrencyGoldIndexDto {
  @IsString()
  terminal_id!: string;

  @IsIn([
    'XAUX',
    'USDX',
    'EURX',
    'JPYX',
    'GBPX',
    'AUDX',
    'NZDX',
    'CADX',
    'CHFX',
  ])
  index_name!: string;

  @IsInt()
  bar_time!: number;

  @IsNumber()
  value!: number;

  @IsNumber()
  change_pct!: number;

  @IsInt()
  session_open_bar_time!: number;
}

// Field-name list, generated alongside the class above, so
// test/dto-contract.spec.ts can check for drift without reflecting into
// class-validator internals.
export const CURRENCY_GOLD_INDEX_DTO_FIELDS = [
  'terminal_id',
  'index_name',
  'bar_time',
  'value',
  'change_pct',
  'session_open_bar_time',
] as const;
