// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by railway-gateway/scripts/generate-market-data-dto.js from
// gateway_contract_economic_events.schema.json. Re-run `npm run generate:dto`
// after any change to that schema file.
import { IsString, IsNumber, IsInt, IsIn, IsOptional } from 'class-validator';

export class EconomicEventDto {
  @IsString()
  terminal_id!: string;

  @IsString()
  value_id!: string;

  @IsInt()
  captured_at!: number;

  @IsString()
  event_id!: string;

  @IsInt()
  event_time!: number;

  @IsInt()
  @IsOptional()
  event_period?: number | null;

  @IsInt()
  @IsOptional()
  revision?: number | null;

  @IsString()
  country_code!: string;

  @IsString()
  currency!: string;

  @IsString()
  event_name!: string;

  @IsIn(['NONE', 'LOW', 'MODERATE', 'HIGH'])
  importance!: string;

  @IsInt()
  @IsOptional()
  event_type?: number | null;

  @IsInt()
  @IsOptional()
  sector?: number | null;

  @IsInt()
  @IsOptional()
  frequency?: number | null;

  @IsInt()
  @IsOptional()
  time_mode?: number | null;

  @IsInt()
  @IsOptional()
  unit?: number | null;

  @IsInt()
  @IsOptional()
  multiplier?: number | null;

  @IsInt()
  @IsOptional()
  digits?: number | null;

  @IsString()
  @IsOptional()
  event_code?: string | null;

  @IsString()
  @IsOptional()
  source_url?: string | null;

  @IsNumber()
  @IsOptional()
  actual_value?: number | null;

  @IsNumber()
  @IsOptional()
  forecast_value?: number | null;

  @IsNumber()
  @IsOptional()
  prev_value?: number | null;

  @IsNumber()
  @IsOptional()
  revised_prev_value?: number | null;

  @IsInt()
  @IsOptional()
  impact_type?: number | null;
}

// Field-name list, generated alongside the class above, so
// test/dto-contract.spec.ts can check for drift without reflecting into
// class-validator internals.
export const ECONOMIC_EVENT_DTO_FIELDS = [
  'terminal_id',
  'value_id',
  'captured_at',
  'event_id',
  'event_time',
  'event_period',
  'revision',
  'country_code',
  'currency',
  'event_name',
  'importance',
  'event_type',
  'sector',
  'frequency',
  'time_mode',
  'unit',
  'multiplier',
  'digits',
  'event_code',
  'source_url',
  'actual_value',
  'forecast_value',
  'prev_value',
  'revised_prev_value',
  'impact_type',
] as const;
