// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by railway-gateway/scripts/generate-market-data-dto.js from
// gateway_contract_indicator_statistics.schema.json. Re-run `npm run generate:dto`
// after any change to that schema file.
import {
  IsString,
  IsNumber,
  IsInt,
  IsIn,
  IsOptional,
  IsBoolean,
  IsObject,
} from 'class-validator';

export class IndicatorStatisticDto {
  @IsString()
  terminal_id!: string;

  @IsIn(['XAUUSD'])
  symbol!: string;

  @IsIn(['M5', 'M15'])
  timeframe!: string;

  @IsIn([
    'best_fit_a',
    'best_fit_b',
    'cherry_a',
    'cherry_b',
    'most_recent',
    'non_a',
    'non_b',
    'fractal_edt',
    'resistance',
    'support',
  ])
  source!: string;

  @IsInt()
  captured_at!: number;

  @IsInt()
  live_bar_ts!: number;

  @IsInt()
  cycle_id!: number;

  @IsBoolean()
  @IsOptional()
  solution_found?: boolean | null;

  @IsNumber()
  @IsOptional()
  raw_slope?: number | null;

  @IsNumber()
  @IsOptional()
  anchored_y_int?: number | null;

  @IsNumber()
  @IsOptional()
  regression_angle?: number | null;

  @IsInt()
  @IsOptional()
  line_origin_ts?: number | null;

  @IsInt()
  @IsOptional()
  touches?: number | null;

  @IsInt()
  @IsOptional()
  window_start_ts?: number | null;

  @IsInt()
  @IsOptional()
  window_end_ts?: number | null;

  @IsInt()
  @IsOptional()
  window_bars?: number | null;

  @IsInt()
  @IsOptional()
  math_lookback?: number | null;

  @IsInt()
  @IsOptional()
  crossings_n?: number | null;

  @IsInt()
  @IsOptional()
  model_a_n?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_r2?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_mse?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_var_ratio?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_skew?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_kurt?: number | null;

  @IsInt()
  @IsOptional()
  model_b_n?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_r2?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_mse?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_var_ratio?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_skew?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_kurt?: number | null;

  @IsNumber()
  @IsOptional()
  uoedt_offset?: number | null;

  @IsNumber()
  @IsOptional()
  loedt_offset?: number | null;

  @IsInt()
  @IsOptional()
  containment_n?: number | null;

  @IsInt()
  @IsOptional()
  containment_count?: number | null;

  @IsNumber()
  @IsOptional()
  containment_rate?: number | null;

  @IsString()
  config_hash!: string;

  @IsObject()
  config_params!: Record<string, unknown>;
}

// Field-name list, generated alongside the class above, so
// test/dto-contract.spec.ts can check for drift without reflecting into
// class-validator internals.
export const INDICATOR_STATISTIC_DTO_FIELDS = [
  'terminal_id',
  'symbol',
  'timeframe',
  'source',
  'captured_at',
  'live_bar_ts',
  'cycle_id',
  'solution_found',
  'raw_slope',
  'anchored_y_int',
  'regression_angle',
  'line_origin_ts',
  'touches',
  'window_start_ts',
  'window_end_ts',
  'window_bars',
  'math_lookback',
  'crossings_n',
  'model_a_n',
  'model_a_r2',
  'model_a_mse',
  'model_a_var_ratio',
  'model_a_skew',
  'model_a_kurt',
  'model_b_n',
  'model_b_r2',
  'model_b_mse',
  'model_b_var_ratio',
  'model_b_skew',
  'model_b_kurt',
  'uoedt_offset',
  'loedt_offset',
  'containment_n',
  'containment_count',
  'containment_rate',
  'config_hash',
  'config_params',
] as const;
