// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by railway-gateway/scripts/generate-market-data-dto.js from
// gateway_contract_indicator_statistics.schema.json. Re-run `npm run generate:dto`
// after any change to that schema file.
import {
  IsString,
  IsNumber,
  IsInt,
  IsIn,
  IsOptional,
  IsBoolean,
  IsObject,
} from 'class-validator';

export class IndicatorStatisticDto {
  @IsString()
  terminal_id!: string;

  @IsIn(['XAUUSD'])
  symbol!: string;

  @IsIn(['M5', 'M15'])
  timeframe!: string;

  @IsIn([
    'best_fit_a',
    'best_fit_b',
    'cherry_a',
    'cherry_b',
    'most_recent',
    'non_a',
    'non_b',
    'fractal_edt',
    'resistance',
    'support',
    'sr_levels',
  ])
  source!: string;

  @IsInt()
  captured_at!: number;

  @IsInt()
  live_bar_ts!: number;

  @IsInt()
  cycle_id!: number;

  @IsBoolean()
  @IsOptional()
  solution_found?: boolean | null;

  @IsNumber()
  @IsOptional()
  raw_slope?: number | null;

  @IsNumber()
  @IsOptional()
  anchored_y_int?: number | null;

  @IsNumber()
  @IsOptional()
  regression_angle?: number | null;

  @IsInt()
  @IsOptional()
  line_origin_ts?: number | null;

  @IsInt()
  @IsOptional()
  touches?: number | null;

  @IsInt()
  @IsOptional()
  window_start_ts?: number | null;

  @IsInt()
  @IsOptional()
  window_end_ts?: number | null;

  @IsInt()
  @IsOptional()
  window_bars?: number | null;

  @IsInt()
  @IsOptional()
  math_lookback?: number | null;

  @IsInt()
  @IsOptional()
  crossings_n?: number | null;

  @IsInt()
  @IsOptional()
  model_a_n?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_r2?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_mse?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_var_ratio?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_skew?: number | null;

  @IsNumber()
  @IsOptional()
  model_a_kurt?: number | null;

  @IsInt()
  @IsOptional()
  model_b_n?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_r2?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_mse?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_var_ratio?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_skew?: number | null;

  @IsNumber()
  @IsOptional()
  model_b_kurt?: number | null;

  @IsNumber()
  @IsOptional()
  uoedt_offset?: number | null;

  @IsNumber()
  @IsOptional()
  loedt_offset?: number | null;

  @IsInt()
  @IsOptional()
  containment_n?: number | null;

  @IsInt()
  @IsOptional()
  containment_count?: number | null;

  @IsNumber()
  @IsOptional()
  containment_rate?: number | null;

  @IsString()
  @IsOptional()
  _extended_note?: string;

  @IsInt()
  @IsOptional()
  window_span_bars?: number | null;

  @IsInt()
  @IsOptional()
  visual_window_bars?: number | null;

  @IsInt()
  @IsOptional()
  bars_available?: number | null;

  @IsInt()
  @IsOptional()
  leftmost_bar_index?: number | null;

  @IsInt()
  @IsOptional()
  line_span_bars?: number | null;

  @IsInt()
  @IsOptional()
  baseline_coverage_n?: number | null;

  @IsNumber()
  @IsOptional()
  baseline_coverage_rate?: number | null;

  @IsInt()
  @IsOptional()
  centroids_used?: number | null;

  @IsInt()
  @IsOptional()
  crossings_in_window_n?: number | null;

  @IsInt()
  @IsOptional()
  first_crossing_ts?: number | null;

  @IsInt()
  @IsOptional()
  last_crossing_ts?: number | null;

  @IsNumber()
  @IsOptional()
  live_close?: number | null;

  @IsNumber()
  @IsOptional()
  baseline_value?: number | null;

  @IsNumber()
  @IsOptional()
  uoedt_value?: number | null;

  @IsNumber()
  @IsOptional()
  loedt_value?: number | null;

  @IsNumber()
  @IsOptional()
  dist_to_baseline?: number | null;

  @IsNumber()
  @IsOptional()
  dist_to_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  dist_to_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  channel_position?: number | null;

  @IsNumber()
  @IsOptional()
  window_high?: number | null;

  @IsNumber()
  @IsOptional()
  window_low?: number | null;

  @IsNumber()
  @IsOptional()
  window_range?: number | null;

  @IsNumber()
  @IsOptional()
  channel_width?: number | null;

  @IsNumber()
  @IsOptional()
  channel_asymmetry?: number | null;

  @IsInt()
  @IsOptional()
  breach_above_n?: number | null;

  @IsInt()
  @IsOptional()
  breach_below_n?: number | null;

  @IsNumber()
  @IsOptional()
  max_excursion_above?: number | null;

  @IsNumber()
  @IsOptional()
  max_excursion_below?: number | null;

  @IsInt()
  @IsOptional()
  resid_a_n?: number | null;

  @IsNumber()
  @IsOptional()
  resid_a_mean?: number | null;

  @IsNumber()
  @IsOptional()
  resid_a_mae?: number | null;

  @IsNumber()
  @IsOptional()
  resid_a_sd?: number | null;

  @IsNumber()
  @IsOptional()
  resid_a_max?: number | null;

  @IsNumber()
  @IsOptional()
  resid_a_dw?: number | null;

  @IsInt()
  @IsOptional()
  resid_b_n?: number | null;

  @IsNumber()
  @IsOptional()
  resid_b_mean?: number | null;

  @IsNumber()
  @IsOptional()
  resid_b_mae?: number | null;

  @IsNumber()
  @IsOptional()
  resid_b_sd?: number | null;

  @IsNumber()
  @IsOptional()
  resid_b_max?: number | null;

  @IsNumber()
  @IsOptional()
  resid_b_dw?: number | null;

  @IsString()
  @IsOptional()
  _sr_note?: string;

  @IsInt()
  @IsOptional()
  sr_fractals_n?: number | null;

  @IsNumber()
  @IsOptional()
  sr_q25?: number | null;

  @IsNumber()
  @IsOptional()
  sr_q75?: number | null;

  @IsNumber()
  @IsOptional()
  sr_iqr?: number | null;

  @IsNumber()
  @IsOptional()
  sr_optimal_step?: number | null;

  @IsInt()
  @IsOptional()
  sr_macro_clusters?: number | null;

  @IsNumber()
  @IsOptional()
  sr_nearest_resistance?: number | null;

  @IsNumber()
  @IsOptional()
  sr_nearest_support?: number | null;

  @IsInt()
  @IsOptional()
  sr_dist_resistance_pts?: number | null;

  @IsInt()
  @IsOptional()
  sr_dist_support_pts?: number | null;

  @IsString()
  config_hash!: string;

  @IsObject()
  config_params!: Record<string, unknown>;
}

// Field-name list, generated alongside the class above, so
// test/dto-contract.spec.ts can check for drift without reflecting into
// class-validator internals.
export const INDICATOR_STATISTIC_DTO_FIELDS = [
  'terminal_id',
  'symbol',
  'timeframe',
  'source',
  'captured_at',
  'live_bar_ts',
  'cycle_id',
  'solution_found',
  'raw_slope',
  'anchored_y_int',
  'regression_angle',
  'line_origin_ts',
  'touches',
  'window_start_ts',
  'window_end_ts',
  'window_bars',
  'math_lookback',
  'crossings_n',
  'model_a_n',
  'model_a_r2',
  'model_a_mse',
  'model_a_var_ratio',
  'model_a_skew',
  'model_a_kurt',
  'model_b_n',
  'model_b_r2',
  'model_b_mse',
  'model_b_var_ratio',
  'model_b_skew',
  'model_b_kurt',
  'uoedt_offset',
  'loedt_offset',
  'containment_n',
  'containment_count',
  'containment_rate',
  '_extended_note',
  'window_span_bars',
  'visual_window_bars',
  'bars_available',
  'leftmost_bar_index',
  'line_span_bars',
  'baseline_coverage_n',
  'baseline_coverage_rate',
  'centroids_used',
  'crossings_in_window_n',
  'first_crossing_ts',
  'last_crossing_ts',
  'live_close',
  'baseline_value',
  'uoedt_value',
  'loedt_value',
  'dist_to_baseline',
  'dist_to_uoedt',
  'dist_to_loedt',
  'channel_position',
  'window_high',
  'window_low',
  'window_range',
  'channel_width',
  'channel_asymmetry',
  'breach_above_n',
  'breach_below_n',
  'max_excursion_above',
  'max_excursion_below',
  'resid_a_n',
  'resid_a_mean',
  'resid_a_mae',
  'resid_a_sd',
  'resid_a_max',
  'resid_a_dw',
  'resid_b_n',
  'resid_b_mean',
  'resid_b_mae',
  'resid_b_sd',
  'resid_b_max',
  'resid_b_dw',
  '_sr_note',
  'sr_fractals_n',
  'sr_q25',
  'sr_q75',
  'sr_iqr',
  'sr_optimal_step',
  'sr_macro_clusters',
  'sr_nearest_resistance',
  'sr_nearest_support',
  'sr_dist_resistance_pts',
  'sr_dist_support_pts',
  'config_hash',
  'config_params',
] as const;
