// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by railway-gateway/scripts/generate-market-data-dto.js from
// gateway_contract_market_data.schema.json. Re-run `npm run generate:dto`
// after any change to that schema file.
import { IsString, IsNumber, IsInt, IsIn, IsOptional } from 'class-validator';

export class MarketDataDto {
  @IsString()
  terminal_id!: string;

  @IsInt()
  timestamp!: number;

  @IsIn(['XAUUSD'])
  symbol!: string;

  @IsIn(['M5', 'M15'])
  timeframe!: string;

  @IsNumber()
  open!: number;

  @IsNumber()
  high!: number;

  @IsNumber()
  low!: number;

  @IsNumber()
  close!: number;

  @IsInt()
  volume!: number;

  @IsNumber()
  @IsOptional()
  best_fit_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  best_fit_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  best_fit_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  cherry_a_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_a_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  cherry_b_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  cherry_b_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  most_recent_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  most_recent_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  non_a_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  non_a_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_horiz_high_map?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_horiz_low_map?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_ssa?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_ema_ssa?: number | null;

  @IsInt()
  @IsOptional()
  non_b_crossing?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_base_fl?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  non_b_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  fractal_best_fl?: number | null;

  @IsNumber()
  @IsOptional()
  fractal_uoedt?: number | null;

  @IsNumber()
  @IsOptional()
  fractal_loedt?: number | null;

  @IsNumber()
  @IsOptional()
  best_resistance?: number | null;

  @IsNumber()
  @IsOptional()
  best_support?: number | null;

  @IsIn([-1, 0, 1])
  @IsOptional()
  body_direction?: number | null;

  @IsNumber()
  @IsOptional()
  body_size?: number | null;

  @IsInt()
  @IsOptional()
  body_classification?: number | null;

  @IsIn(['Peak', 'Bottom'])
  @IsOptional()
  zigzag_point_type?: string | null;

  @IsNumber()
  @IsOptional()
  zigzag_current_point?: number | null;

  @IsNumber()
  @IsOptional()
  zigzag_price_change?: number | null;

  @IsNumber()
  @IsOptional()
  zigzag_pct_change?: number | null;

  @IsInt()
  @IsOptional()
  zigzag_pct_change_class?: number | null;

  @IsInt()
  @IsOptional()
  zigzag_bars?: number | null;

  @IsInt()
  @IsOptional()
  zigzag_bars_class?: number | null;

  @IsNumber()
  @IsOptional()
  zigzag_price_per_bar?: number | null;

  @IsInt()
  @IsOptional()
  zigzag_price_per_bar_class?: number | null;

  @IsNumber()
  @IsOptional()
  zigzag_slope?: number | null;

  @IsIn(['HH', 'HL', 'LH', 'LL', 'EQH', 'EQL'])
  @IsOptional()
  zigzag_category?: string | null;

  @IsInt()
  @IsOptional()
  cycle_id?: number | null;

  @IsInt()
  @IsOptional()
  collected_at?: number | null;

  @IsInt()
  @IsOptional()
  calculated_at?: number | null;

}

// Field-name list, generated alongside the class above, so
// test/dto-contract.spec.ts can check for drift without reflecting into
// class-validator internals.
export const MARKET_DATA_DTO_FIELDS = [
  'terminal_id',
  'timestamp',
  'symbol',
  'timeframe',
  'open',
  'high',
  'low',
  'close',
  'volume',
  'best_fit_horiz_high_map',
  'best_fit_horiz_low_map',
  'best_fit_ssa',
  'best_fit_ema_ssa',
  'best_fit_crossing',
  'best_fit_base_fl',
  'best_fit_uoedt',
  'best_fit_loedt',
  'cherry_a_horiz_high_map',
  'cherry_a_horiz_low_map',
  'cherry_a_ssa',
  'cherry_a_ema_ssa',
  'cherry_a_crossing',
  'cherry_a_base_fl',
  'cherry_a_uoedt',
  'cherry_a_loedt',
  'cherry_b_horiz_high_map',
  'cherry_b_horiz_low_map',
  'cherry_b_ssa',
  'cherry_b_ema_ssa',
  'cherry_b_crossing',
  'cherry_b_base_fl',
  'cherry_b_uoedt',
  'cherry_b_loedt',
  'most_recent_horiz_high_map',
  'most_recent_horiz_low_map',
  'most_recent_ssa',
  'most_recent_ema_ssa',
  'most_recent_crossing',
  'most_recent_base_fl',
  'most_recent_uoedt',
  'most_recent_loedt',
  'non_a_horiz_high_map',
  'non_a_horiz_low_map',
  'non_a_ssa',
  'non_a_ema_ssa',
  'non_a_crossing',
  'non_a_base_fl',
  'non_a_uoedt',
  'non_a_loedt',
  'non_b_horiz_high_map',
  'non_b_horiz_low_map',
  'non_b_ssa',
  'non_b_ema_ssa',
  'non_b_crossing',
  'non_b_base_fl',
  'non_b_uoedt',
  'non_b_loedt',
  'fractal_best_fl',
  'fractal_uoedt',
  'fractal_loedt',
  'best_resistance',
  'best_support',
  'body_direction',
  'body_size',
  'body_classification',
  'zigzag_point_type',
  'zigzag_current_point',
  'zigzag_price_change',
  'zigzag_pct_change',
  'zigzag_pct_change_class',
  'zigzag_bars',
  'zigzag_bars_class',
  'zigzag_price_per_bar',
  'zigzag_price_per_bar_class',
  'zigzag_slope',
  'zigzag_category',
  'cycle_id',
  'collected_at',
  'calculated_at',
] as const;
