# generated by datamodel-codegen:
#   filename:  part-06-flask_mt5_openapi.yaml
#   timestamp: 2026-01-24T02:55:36+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, Field


class UserTier(StrEnum):
    """
    User subscription tier for access control:
    - FREE: 5 symbols (BTCUSD, EURUSD, USDJPY, US30, XAUUSD) × 3 timeframes (H1, H4, D1)
    - PRO: 15 symbols × 9 timeframes (M5, M15, M30, H1, H2, H4, H8, H12, D1)

    """

    FREE = "FREE"
    PRO = "PRO"


class Symbol(StrEnum):
    """
    Trading symbols available on platform (15 total).
    Access is tier-based:
    - FREE: BTCUSD, EURUSD, USDJPY, US30, XAUUSD (5 symbols)
    - PRO: All 15 symbols

    """

    AUDJPY = "AUDJPY"
    AUDUSD = "AUDUSD"
    BTCUSD = "BTCUSD"
    ETHUSD = "ETHUSD"
    EURUSD = "EURUSD"
    GBPJPY = "GBPJPY"
    GBPUSD = "GBPUSD"
    NDX100 = "NDX100"
    NZDUSD = "NZDUSD"
    US30 = "US30"
    USDCAD = "USDCAD"
    USDCHF = "USDCHF"
    USDJPY = "USDJPY"
    XAGUSD = "XAGUSD"
    XAUUSD = "XAUUSD"


class Timeframe(StrEnum):
    """
    Chart timeframes (V7 - 9 timeframes).
    FREE tier: H1, H4, D1 (3 timeframes)
    PRO tier: All 9 timeframes (M5, M15, M30, H1, H2, H4, H8, H12, D1)

    """

    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    H2 = "H2"
    H4 = "H4"
    H8 = "H8"
    H12 = "H12"
    D1 = "D1"


class Status(StrEnum):
    """
    Overall service status:
    - ok: All terminals connected
    - degraded: Some terminals disconnected
    - error: All terminals disconnected

    """

    ok = "ok"
    degraded = "degraded"
    error = "error"


class TerminalStatus(BaseModel):
    """
    Status of a single MT5 terminal connection
    """

    connected: bool = Field(
        ..., description="Whether terminal is currently connected", examples=[True]
    )
    terminal_id: str = Field(
        ...,
        description="Terminal identifier (MT5_01 through MT5_15)",
        examples=["MT5_01"],
    )
    last_check: AwareDatetime = Field(
        ...,
        description="Timestamp of last health check",
        examples=["2025-11-17T10:30:00Z"],
    )
    error: str | None = Field(
        None,
        description="Error message if connection failed (only present when connected=false)",
        examples=["Connection timeout"],
    )


class SymbolsResponse(BaseModel):
    success: bool
    tier: UserTier
    symbols: list[Symbol] = Field(..., description="List of symbols accessible by tier")


class TimeframesResponse(BaseModel):
    success: bool
    tier: UserTier
    timeframes: list[Timeframe] = Field(
        ..., description="List of all supported timeframes"
    )


class OHLCVBar(BaseModel):
    """
    Single candlestick bar
    """

    time: int = Field(..., description="Unix timestamp", examples=[1699632000])
    open: float = Field(..., description="Opening price", examples=[1985.5])
    high: float = Field(..., description="Highest price", examples=[1987.25])
    low: float = Field(..., description="Lowest price", examples=[1984.75])
    close: float = Field(..., description="Closing price", examples=[1986.0])
    volume: int = Field(..., description="Tick volume", examples=[1234])


class OHLCVMetadata(BaseModel):
    """
    Metadata about the OHLCV data
    """

    timestamp: int = Field(
        ..., description="Unix timestamp of most recent bar", examples=[1699632000]
    )
    bars_requested: int = Field(
        ..., description="Number of bars requested", examples=[1000]
    )
    bars_received: int = Field(
        ..., description="Actual number of bars received", examples=[1000]
    )
    tier: UserTier
    terminal_id: str = Field(
        ...,
        description="MT5 terminal ID that handled this request (MT5_01 through MT5_15)",
        examples=["MT5_15"],
    )


class AccessDeniedResponse(BaseModel):
    """
    Returned when tier cannot access requested symbol or timeframe
    """

    success: bool = Field(..., examples=[False])
    error: str = Field(
        ...,
        description="Human-readable error message",
        examples=["FREE tier cannot access AUDJPY"],
    )
    tier: UserTier
    accessible_symbols: list[str] | None = Field(
        None,
        description="List of symbols accessible by this tier (present if symbol denied)",
    )
    accessible_timeframes: list[str] | None = Field(
        None,
        description="List of timeframes accessible by this tier (present if timeframe denied)",
    )
    upgrade_required: bool = Field(..., description="Whether upgrade to PRO is needed")


class ErrorResponse(BaseModel):
    """
    Generic error response
    """

    success: bool = Field(..., examples=[False])
    error: str = Field(
        ..., description="Error message", examples=["Failed to retrieve OHLCV data"]
    )


class Status1(StrEnum):
    ok = "ok"
    degraded = "degraded"
    error = "error"


class AdminTerminalStatus(BaseModel):
    """
    Admin view of terminal status with additional metrics
    """

    connected: bool
    terminal_id: str
    last_check: AwareDatetime
    error: str | None = None
    uptime_percentage: float | None = Field(
        None, description="Uptime percentage (0-100)"
    )
    reconnect_count: int | None = Field(None, description="Number of reconnections")
    last_error: str | None = Field(None, description="Last error message (if any)")


class TerminalRestartResponse(BaseModel):
    """
    Response from terminal restart operation
    """

    success: bool
    message: str | None = None
    terminal_id: str
    symbol: str
    connected: bool | None = None
    last_error: str | None = None


class Result(BaseModel):
    terminal_id: str | None = None
    symbol: str | None = None
    success: bool | None = None
    error: str | None = None


class RestartAllResponse(BaseModel):
    """
    Response from restart all terminals operation
    """

    success: bool
    message: str | None = None
    total_terminals: int
    successful_restarts: int
    failed_restarts: int
    results: list[Result]


class Level(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    DEBUG = "DEBUG"


class Log(BaseModel):
    timestamp: AwareDatetime | None = None
    level: Level | None = None
    message: str | None = None


class TerminalLogsResponse(BaseModel):
    """
    Terminal log entries
    """

    success: bool
    terminal_id: str
    symbol: str
    logs: list[Log]


class TerminalsByStatus(BaseModel):
    connected: int | None = None
    disconnected: int | None = None
    reconnecting: int | None = None


class MostProblematicTerminal(BaseModel):
    terminal_id: str | None = None
    symbol: str | None = None
    reconnect_count: int | None = None
    uptime: float | None = None


class Stats(BaseModel):
    total_uptime_percentage: float | None = None
    total_reconnects_24h: int | None = None
    avg_response_time_ms: float | None = None
    terminals_by_status: TerminalsByStatus | None = None
    most_problematic_terminals: list[MostProblematicTerminal] | None = None


class TerminalStatsResponse(BaseModel):
    """
    Aggregate statistics for all terminals
    """

    success: bool
    stats: Stats


class HealthResponse(BaseModel):
    status: Status = Field(
        ...,
        description="Overall service status:\n- ok: All terminals connected\n- degraded: Some terminals disconnected\n- error: All terminals disconnected\n",
    )
    version: str = Field(
        ..., description="Service version identifier", examples=["v6.0.0"]
    )
    total_terminals: int = Field(
        ..., description="Total number of MT5 terminals configured", examples=[15]
    )
    connected_terminals: int = Field(
        ..., description="Number of terminals currently connected", examples=[15]
    )
    terminals: dict[str, TerminalStatus] = Field(
        ...,
        description="Per-symbol terminal connection status",
        examples=[
            {
                "XAUUSD": {
                    "connected": True,
                    "terminal_id": "MT5_15",
                    "last_check": "2025-11-17T10:30:00Z",
                },
                "BTCUSD": {
                    "connected": False,
                    "terminal_id": "MT5_03",
                    "last_check": "2025-11-17T10:30:00Z",
                    "error": "Connection timeout",
                },
            }
        ],
    )


class OHLCVData(BaseModel):
    """
    Complete OHLCV data package from MT5.

    NOTE: This service ONLY provides raw candlestick data.
    For indicators and technical analysis, use Part 20 (SQLite-Sync Script).

    """

    symbol: Symbol
    timeframe: Timeframe
    bars: int = Field(..., description="Number of bars returned", examples=[1000])
    ohlcv: list[OHLCVBar] = Field(..., description="Array of OHLCV candlestick data")
    metadata: OHLCVMetadata


class AdminHealthResponse(BaseModel):
    """
    Admin health response with additional metrics
    """

    status: Status1
    version: str
    total_terminals: int
    connected_terminals: int
    terminals: dict[str, AdminTerminalStatus]


class OHLCVDataResponse(BaseModel):
    success: bool = Field(..., examples=[True])
    data: OHLCVData
