'use client';

import React from 'react';
import Link from 'next/link';
import { ShieldAlert, AlertTriangle, Scale, HelpCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MarketingNavbar } from '@/components/marketing/marketing-navbar';
import { MarketingFooter } from '@/components/marketing/marketing-footer';
import { useLocale } from '@/lib/context/locale-context';

export default function DisclaimerPage() {
  const { t } = useLocale();

  return (
    <div className="flex min-h-screen flex-col bg-[#050609] text-slate-100">
      <MarketingNavbar />

      <main className="container mx-auto max-w-4xl flex-1 px-4 py-16 md:px-6">
        <div className="space-y-8">
          <div className="space-y-3">
            <Badge className="border-rose-500/40 bg-rose-500/15 px-3 py-1 font-mono text-xs text-rose-400">
              {t('Regulatory & Risk Notice', 'ประกาศกฎหมายและความเสี่ยง')}
            </Badge>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-100 md:text-4xl">
              {t(
                'Financial Risk Disclosure & Legal Disclaimer',
                'การเปิดเผยความเสี่ยงทางการเงินและข้อสงวนสิทธิ์'
              )}
            </h1>
            <p className="text-sm text-slate-400">
              {t('Last Updated: August 2026', 'อัปเดตล่าสุด: สิงหาคม 2026')}
            </p>
          </div>

          <Card className="border-rose-500/30 bg-rose-950/20 backdrop-blur-xl">
            <CardContent className="flex items-start gap-4 p-6">
              <ShieldAlert className="mt-0.5 h-7 w-7 shrink-0 text-rose-400" />
              <div className="space-y-2">
                <h3 className="text-base font-bold text-rose-200">
                  {t(
                    'High Risk Investment Warning',
                    'คำเตือนการลงทุนที่มีความเสี่ยงสูง'
                  )}
                </h3>
                <p className="text-xs leading-relaxed text-slate-300">
                  {t(
                    'Trading Foreign Exchange (Forex), Contracts for Difference (CFDs), and Commodities such as Spot Gold (XAUUSD) on margin carries a high level of risk and may not be suitable for all investors. The high degree of leverage can work against you as well as for you. You may lose some or all of your invested capital.',
                    'การซื้อขายฟอเร็กซ์ สัญญาซื้อขายส่วนต่าง (CFDs) และสินค้าโภคภัณฑ์เช่นทองคำ (XAUUSD) บนมาร์จินมีความเสี่ยงสูง และอาจไม่เหมาะสมกับนักลงทุนทุกคน เลเวอเรจในระดับสูงอาจสร้างผลขาดทุนเช่นเดียวกับผลกำไร คุณอาจสูญเสียเงินลงทุนบางส่วนหรือทั้งหมด'
                  )}
                </p>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-6 border-t border-slate-800/80 pt-6 text-sm leading-relaxed text-slate-300">
            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                1.{' '}
                {t(
                  'Informational and Educational Purpose Only',
                  'เพื่อวัตถุประสงค์ในการให้ข้อมูลและการศึกษาเท่านั้น'
                )}
              </h2>
              <p>
                {t(
                  'DavinTrade AI is an algorithmic quantitative analytics software platform. All automated alerts, chart annotations, AI conversational outputs, fractal indicators, and momentum models are strictly generated by automated computer algorithms for informational and analytical assistance.',
                  'DavinTrade AI เป็นแพลตฟอร์มซอฟต์แวร์วิเคราะห์ข้อมูลเชิงปริมาณ สัญญาณเตือนอัตโนมัติ คำอธิบายกราฟ ผลลัพธ์จาก AI สนทนา ตัวบ่งชี้แฟร็กทัล และโมเดลโมเมนตัมทั้งหมดถูกสร้างขึ้นโดยอัลกอริทึมคอมพิวเตอร์อัตโนมัติเพื่อการวิเคราะห์และเป็นข้อมูลอ้างอิงเท่านั้น'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                2.{' '}
                {t(
                  'No Financial or Investment Advice',
                  'มิใช่คำแนะนำทางการเงินหรือการลงทุน'
                )}
              </h2>
              <p>
                {t(
                  'Nothing on this platform, website, or conversational assistant constitutes an offer to buy or sell financial instruments, nor does it constitute personal financial, tax, or investment advice. You alone assume the sole responsibility of evaluating the merits and risks associated with any trading decision.',
                  'ไม่มีเนื้อหาใดบนแพลตฟอร์ม เว็บไซต์ หรือผู้ช่วย AI นี้ที่ถือเป็นข้อเสนอในการซื้อหรือขายตราสารทางการเงิน หรือถือเป็นคำแนะนำทางการเงิน ภาษี หรือการลงทุนส่วนบุคคล คุณเป็นผู้รับผิดชอบแต่เพียงผู้เดียวในการประเมินข้อดีและความเสี่ยงในการตัดสินใจเทรด'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                3.{' '}
                {t(
                  'Hypothetical & Past Performance',
                  'ผลการดำเนินงานในอดีตและผลการทดสอบ'
                )}
              </h2>
              <p>
                {t(
                  'Past performance results and backtested algorithmic scenarios are no guarantee of future returns. Market conditions are dynamic and unpredictable. No representation is being made that any account will or is likely to achieve profits or losses similar to those discussed on this platform.',
                  'ผลการดำเนินงานในอดีตและสถานการณ์ทดสอบย้อนหลังไม่ได้รับประกันผลตอบแทนในอนาคต สภาวะตลาดมีความผันผวนและไม่อาจคาดการณ์ได้ ไม่มีการรับรองว่าบัญชีใดๆ จะได้รับกำไรหรือขาดทุนตามแบบจำลองที่แสดงบนแพลตฟอร์ม'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                4.{' '}
                {t(
                  'Technical Reliability & Latency',
                  'ความเสถียรทางเทคนิคและความล่าช้า'
                )}
              </h2>
              <p>
                {t(
                  'While DavinTrade AI strives to maintain sub-second data throughput via MetaTrader 5 (MT5) gateways and redundant WebSocket infrastructure, network disruptions, broker server lags, or internet connection outages may delay or distort real-time alerts. DavinTrade AI accepts no liability for losses resulting from connectivity failures.',
                  'แม้ว่า DavinTrade AI จะพยายามรักษาการส่งข้อมูลความเร็วสูงผ่านเกตเวย์ MetaTrader 5 (MT5) และโครงสร้างพื้นฐาน WebSocket สำรอง แต่อาจเกิดความล่าช้าจากเครือข่าย ปัญหาเซิร์ฟเวอร์โบรกเกอร์ หรืออินเทอร์เน็ตขัดข้องได้ DavinTrade AI ไม่รับผิดชอบต่อความสูญเสียจากปัญหาการเชื่อมต่อ'
                )}
              </p>
            </section>
          </div>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
