'use client';

import React from 'react';
import Link from 'next/link';
import { ShieldAlert, AlertTriangle, Scale, HelpCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MarketingNavbar } from '@/components/marketing/marketing-navbar';
import { MarketingFooter } from '@/components/marketing/marketing-footer';
import { useLocale } from '@/lib/context/locale-context';

export default function DisclaimerPage() {
  const { t } = useLocale();

  return (
    <div className="flex min-h-screen flex-col bg-[#050609] text-slate-100">
      <MarketingNavbar />

      <main className="container mx-auto max-w-4xl flex-1 px-4 py-16 md:px-6">
        <div className="space-y-8">
          <div className="space-y-3">
            <Badge className="border-rose-500/40 bg-rose-500/15 px-3 py-1 font-mono text-xs text-rose-400">
              {t('Regulatory & Risk Notice')}
            </Badge>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-100 md:text-4xl">
              {t('Financial Risk Disclosure & Legal Disclaimer')}
            </h1>
            <p className="text-sm text-slate-400">
              {t('Last Updated: August 2026')}
            </p>
          </div>

          <Card className="border-rose-500/30 bg-rose-950/20 backdrop-blur-xl">
            <CardContent className="flex items-start gap-4 p-6">
              <ShieldAlert className="mt-0.5 h-7 w-7 shrink-0 text-rose-400" />
              <div className="space-y-2">
                <h3 className="text-base font-bold text-rose-200">
                  {t('High Risk Investment Warning')}
                </h3>
                <p className="text-xs leading-relaxed text-slate-300">
                  {t(
                    'Trading Foreign Exchange (Forex), Contracts for Difference (CFDs), and Commodities such as Spot Gold (XAUUSD) on margin carries a high level of risk and may not be suitable for all investors. The high degree of leverage can work against you as well as for you. You may lose some or all of your invested capital.'
                  )}
                </p>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-6 border-t border-slate-800/80 pt-6 text-sm leading-relaxed text-slate-300">
            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                1. {t('Informational and Educational Purpose Only')}
              </h2>
              <p>
                {t(
                  'DavinTrade AI is an algorithmic quantitative analytics software platform. All automated alerts, chart annotations, AI conversational outputs, fractal indicators, and momentum models are strictly generated by automated computer algorithms for informational and analytical assistance.'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                2. {t('No Financial or Investment Advice')}
              </h2>
              <p>
                {t(
                  'Nothing on this platform, website, or conversational assistant constitutes an offer to buy or sell financial instruments, nor does it constitute personal financial, tax, or investment advice. You alone assume the sole responsibility of evaluating the merits and risks associated with any trading decision.'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                3. {t('Hypothetical & Past Performance')}
              </h2>
              <p>
                {t(
                  'Past performance results and backtested algorithmic scenarios are no guarantee of future returns. Market conditions are dynamic and unpredictable. No representation is being made that any account will or is likely to achieve profits or losses similar to those discussed on this platform.'
                )}
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-100">
                4. {t('Technical Reliability & Latency')}
              </h2>
              <p>
                {t(
                  'While DavinTrade AI strives to maintain sub-second data throughput via MetaTrader 5 (MT5) gateways and redundant WebSocket infrastructure, network disruptions, broker server lags, or internet connection outages may delay or distort real-time alerts. DavinTrade AI accepts no liability for losses resulting from connectivity failures.'
                )}
              </p>
            </section>
          </div>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
